# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CopilotCouncil < Formula
  desc "AI Model Council Pattern CLI - Query multiple AI models and aggregate responses"
  homepage "https://github.com/openjny/copilot-council"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openjny/copilot-council/releases/download/v0.1.2/copilot-council_0.1.2_darwin_amd64.tar.gz"
      sha256 "bb348a266c7edd6f8a11766467daa70cb161a05bd0d2fc145726cba9945015a9"

      def install
        bin.install "copilot-council"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openjny/copilot-council/releases/download/v0.1.2/copilot-council_0.1.2_darwin_arm64.tar.gz"
      sha256 "9ccebadbc1813270bf0e2468a07df3a64fe005baa36dfad532978fdfc37c71af"

      def install
        bin.install "copilot-council"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openjny/copilot-council/releases/download/v0.1.2/copilot-council_0.1.2_linux_amd64.tar.gz"
      sha256 "8785d7fbee04bf5e8fb890e892f619e0cd8b3ba6c66cb878ba44066b0388301c"
      def install
        bin.install "copilot-council"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openjny/copilot-council/releases/download/v0.1.2/copilot-council_0.1.2_linux_arm64.tar.gz"
      sha256 "9b045d158e24fa7d8ae1333546c527c96863d70e0c3f2353933f961f91097f19"
      def install
        bin.install "copilot-council"
      end
    end
  end

  test do
    system "#{bin}/copilot-council --version"
  end
end
