# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CopilotCouncil < Formula
  desc "AI Model Council Pattern CLI - Query multiple AI models and aggregate responses"
  homepage "https://github.com/openjny/copilot-council"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openjny/copilot-council/releases/download/v0.1.0/copilot-council_0.1.0_darwin_amd64.tar.gz"
      sha256 "0fca2948b099d9415dfbc11f26df8d17f880196dfeb5b6310bdb4871c779461d"

      def install
        bin.install "copilot-council"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openjny/copilot-council/releases/download/v0.1.0/copilot-council_0.1.0_darwin_arm64.tar.gz"
      sha256 "085d2637a4dc55099daa17a0800da8d5e9e21038f1419067e2cb9487e56255af"

      def install
        bin.install "copilot-council"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openjny/copilot-council/releases/download/v0.1.0/copilot-council_0.1.0_linux_amd64.tar.gz"
      sha256 "c64ef603122bfdce51c24f166d0588b3239b99efbdd4bc0ca2ba5bd3d72e441e"
      def install
        bin.install "copilot-council"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openjny/copilot-council/releases/download/v0.1.0/copilot-council_0.1.0_linux_arm64.tar.gz"
      sha256 "100728d62c035ea986c6dce7fa8a3a7f8a0847b973ca50d64d42bce540486348"
      def install
        bin.install "copilot-council"
      end
    end
  end

  test do
    system "#{bin}/copilot-council --version"
  end
end
